{{- if .Values.imageCredentials.pullSecret }}
{{- else if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctai.fullname" . }}-pull-secret
  labels:
    {{- include "ctai.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "ctai.imagePullSecret" . }}
{{- end }}
