{{- if eq (include "ctai.propertiesFromChart" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctai.propertiesSecretName" . }}
  labels:
    {{- include "ctai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.properties.fileName }}: |-
{{ .Values.ctaiPropertiesFile | nindent 4 }}
{{- end }}
