environment: production
replicaCount: 2
image:
  tag: dev-6a0ed36693d3b7ce4fd1b1141a160a24e9ec8ba6

ingress:
  enabled: false
  hosts:
    - host: app.codetogether.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi 