environment: production
replicaCount: 2
image:
  tag: c819a2996f8d96cfcadc73cba625d01d70f8df2b

ingress:
  hosts:
    - host: app.codetogether.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi 