apiVersion: v2
name: codetogether-ai
description: CodeTogether AI on-premises Kubernetes deployment

type: application
version: 0.1.0
appVersion: "0.1.1204"

icon: https://www.codetogether.com/wp-content/uploads/2020/02/codetogether-circle-128.png
home: https://www.codetogether.com

maintainers:
  - email: info@codetogether.com
    name: CodeTogether Inc.

keywords:
  - codetogether
  - ctai
  - ai
  - aitrax
  - on-premises
