apiVersion: v2
name: codetogether
description: CodeTogether Live provides pair programming and collaborative coding

type: application
version: 1.4.19
appVersion: "2024.1.0"
kubeVersion: ">= 1.18.0"

icon: https://www.codetogether.com/wp-content/uploads/2020/02/codetogether-circle-128.png
home: https://www.codetogether.com

maintainers:
- email: info@codetogether.com
  name: CodeTogether Inc.

keywords:
- codetogether
- live
- collaborative
- pair
- programming
