apiVersion: v1
kind: Secret
metadata:
  name: hqproperties
type: Opaque
stringData:
  cthq.properties: |-
    {{- range $key, $value := .Values.hqproperties }}
       {{ $key }}={{ $value }}
    {{- end }}