services: 
  codetogether-hq:
    image: hub.edge.codetogether.com/releases/codetogether-hq:latest
    container_name: codetogether-hq
    environment:
      - CT_HQ_BASE_URL=https://your-hq-server-fqdn
    networks:
      - hqnet
    volumes:
      - ./cthq.properties:/opt/codetogether/runtime/cthq.properties:ro
    ports:
      - "1080:1080"
    depends_on:
      cassandra:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grep", "-q", "CodeTogether HQ backend started", "/var/log/codetogether-runtime/server.log"]
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 20
  cassandra:
    image: cassandra:latest
    container_name: codetogether-cassandra
    networks:
      - hqnet
    environment:
      - HEAP_NEWSIZE=96M
      - MAX_HEAP_SIZE=512M
    volumes:
      - ./cassandra-config.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-init.cql:/scripts/init.sql
      - ./cassandra-startup.sh:/scripts/startup.sh
      - ./data:/var/lib/cassandra
    entrypoint: /scripts/startup.sh
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/cassandra-ready"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 20
networks:
  hqnet:
    driver: bridge
