services: 
  codetogether-collab:
    image: hub.edge.codetogether.com/releases/codetogether-collab:latest
    container_name: codetogether-collab
    environment:
      # your collab/pair programming server URL
      - CT_SERVER_URL=https://your-collab-server-fqdn
      - CT_INTEL_URL=http://codetogether-intel:1080
      - CT_INTEL_SECRET=your-collab-intel-secret
      - CT_AV_ENABLED=false
      - CT_AV_LAN_IP=auto
    networks:
      - codetogethernet
    depends_on:
       codetogether-intel:
        condition: service_healthy
  nginx:
    image: nginx:latest
    container_name: codetogether-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
    networks:
      - codetogethernet
    depends_on:
       codetogether-intel:
        condition: service_healthy
  codetogether-intel:
    image: hub.edge.codetogether.com/releases/codetogether-intel:latest
    container_name: codetogether-intel
    environment:
      - CT_HQ_BASE_URL=https://your-intel-server-fqdn
    networks:
      - codetogethernet
    volumes:
      - ./cthq.properties:/opt/codetogether/runtime/cthq.properties:ro
    ports:
      - "1080:1080"
    depends_on:
      cassandra:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grep", "-q", "CodeTogether Intel backend started", "/var/log/codetogether-runtime/server.log"]
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 50
  cassandra:
    image: cassandra:latest
    container_name: codetogether-cassandra
    ports: 
      - 9042:9042
    networks:
      - codetogethernet
    environment:
      - HEAP_NEWSIZE=96M
      - MAX_HEAP_SIZE=512M
    volumes:
      - ./cassandra-config.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-init.cql:/scripts/init.sql
      - ./cassandra-startup.sh:/scripts/startup.sh
      - ./data:/var/lib/cassandra
    entrypoint: ["/bin/sh", "-c", "chmod +x /scripts/startup.sh && /scripts/startup.sh"]
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/cassandra-ready"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 70
networks:
  codetogethernet:
    driver: bridge