apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-license
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.license.url | b64enc | quote }}
  token: {{ .Values.license.token | b64enc | quote }}
