apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codetogether.fullname" . }}
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "codetogether.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/coturn: {{ include (print $.Template.BasePath "/secret-coturn.yaml") . | sha256sum }}
        checksum/dashboard: {{ include (print $.Template.BasePath "/secret-dashboard.yaml") . | sha256sum }}
        checksum/intel: {{- if not .Values.intelsecret.enabled }} {{ include (print $.Template.BasePath "/secret-intel.yaml") . | sha256sum }} {{- else }} "external" {{- end }}
        checksum/ssl: {{ include (print $.Template.BasePath "/secret-ssl.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codetogether.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecret }}
      {{- else if eq .Values.imageCredentials.enabled true }}
      imagePullSecrets:
        - name: {{ include "codetogether.fullname" . }}-pull-secret
      {{- end }}
      serviceAccountName: {{ include "codetogether.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: >-
            {{ .Values.image.repository }}
            {{- if .Values.image.digest }}@{{ .Values.image.digest }}
            {{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
          #
          # Set CodeTogether runtime configuration
          #         
          - name: CT_SERVER_URL
            value: {{ .Values.codetogether.url | quote }}
          - name: CT_TRUST_ALL_CERTS
            value: {{ .Values.codetogether.trustAllCerts | quote }}

          {{- if eq .Values.codetogether.mode "direct" }}
          - name: CT_LOCATOR
            value: "none"
          - name: CT_PROMETHEUS_ENABLED
            value: {{ .Values.direct.metrics.prometheusEnabled | quote }}         
          {{- if .Values.direct.metrics.statsdEnabled }}
          - name: CT_METRICS_STATSD_HOST
            value: {{ .Values.direct.metrics.statsdHost | quote }}
          - name: CT_METRICS_STATSD_PORT
            value: {{ .Values.direct.metrics.statsdPort | quote }}
          - name: CT_METRICS_STATSD_PROTOCOL
            value: {{ .Values.direct.metrics.statsdProtocol | quote }}
          {{- end }}
          {{- end }}

          {{- if eq .Values.codetogether.noclients "true" }}
          - name: CT_NOCLIENTS
            value: "true"
          {{- end }}

          {{- if eq .Values.codetogether.mode "locator-central" }}
          - name: CT_LOCATOR
            value: {{ .Values.codetogether.url | quote }}
          - name: CT_LOCATOR_CONFIG
            value: {{ .Values.locatorCentral | toJson | quote }}
          {{- end }}
          {{- if .Values.locatorCentral.database.sslKey }}
          - name: CT_DB_SSL_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.fullname" . }}-ssl
                key: key
          {{- end }}
          {{- if .Values.locatorCentral.database.sslCert }}
          - name: CT_DB_SSL_CERT
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.fullname" . }}-ssl
                key: cert
          {{- end }}
          {{- if .Values.locatorCentral.database.sslCA }}
          - name: CT_DB_SSL_CA
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.fullname" . }}-ssl
                key: ca
          {{- end }}

          {{- if eq .Values.codetogether.mode "locator-edge" }}
          - name: CT_LOCATOR
            value: {{ .Values.locatorEdge.locator | quote }}
          {{- if .Values.locatorEdge.locatorLan }}
          - name: CT_LOCATOR_INTERNAL
            value: {{ .Values.locatorEdge.locatorLan | quote }}
          {{- end }}
          - name: CT_REGION
            value: {{ .Values.locatorEdge.region | quote }}
          {{- end }}  

          {{- if or (eq .Values.codetogether.mode "direct") (eq .Values.codetogether.mode "locator-edge") }}
          - name: CT_AV_ENABLED
            value: {{ .Values.av.enabled | quote }}
          {{- if .Values.av.enabled }} 
          - name: CT_AV_LAN_IP
            value: {{ .Values.av.serverIP | quote }}
          {{- end }}
          {{- else }}
          - name: CT_AV_ENABLED
            value: "false"
          {{- end }}

          {{- if .Values.av.stunServers.enabled }}
          - name: CT_AV_COTURN_SERVER
            value: {{ .Values.av.stunServers.server | quote }}
          - name: CT_AV_COTURN_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.fullname" . }}-coturn
                key: secret
          {{- end }}

          {{- if and .Values.av.jitsiUrl (ne .Values.av.jitsiUrl "") }}
          - name: CT_JITSI_URL
            value: {{ .Values.av.jitsiUrl | quote }}
          {{- end }}

          {{- if .Values.codetogether.timeZone.enabled }}
          - name: CT_TIME_ZONE
            value: {{ .Values.codetogether.timeZone.region | quote }}
          {{- end }}

          {{- if and .Values.intelsecret.enabled (not .Values.intelsecret.ref) }}
          {{- fail "intelsecret.enabled=true requires intelsecret.ref (existing Secret name)" -}}
          {{- end }}

          - name: CT_INTEL_URL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.intelsecret.enabled -}}
                        {{ .Values.intelsecret.ref | quote }}
                      {{- else }}
                        {{ printf "%s-intel" (include "codetogether.fullname" .) | quote }}
                      {{- end }}
                key: url
          - name: CT_INTEL_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.intelsecret.enabled -}}
                        {{ .Values.intelsecret.ref | quote }}
                      {{- else }}
                        {{ printf "%s-intel" (include "codetogether.fullname" .) | quote }}
                      {{- end }}
                key: secret
          {{- if .Values.dashboard.enabled }}
          - name: CT_DASHBOARD_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.dashboardSecretName" . }}
                key: username
          - name: CT_DASHBOARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.dashboardSecretName" . }}
                key: password
          {{- end }}
          {{- if .Values.proxy.enabled }}
          - name: CT_PROXY
            valueFrom:
              secretKeyRef:
                name: {{ include "codetogether.proxy.secretName" . }}
                key: proxy-uri
          {{- end}}
          {{- if .Values.restart.enabled }}
          - name: CT_AUTO_RESTART_CRON_PATTERN
            value: {{ .Values.restart.cronPattern | quote }}
          {{- else }}
          - name: CT_AUTO_RESTART_DISABLED
            value: "true"
          {{- end }}

          {{- if .Values.securityContext.readOnlyRootFilesystem}}
          volumeMounts:
            - mountPath: /run
              name: codetogether-runtime
            - mountPath: /tmp
              name: codetogether-tmp
            {{- if .Values.favicon.enabled }}
            - mountPath: /opt/volatile-template/nginx/favicon.ico
              name: favicon-volume
              subPath: favicon.ico
            {{- end }}
          {{- else if .Values.favicon.enabled }}
          volumeMounts:
            - mountPath: /opt/volatile-template/nginx/favicon.ico
              name: favicon-volume
              subPath: favicon.ico
          {{- end }}

          # 
          # Set container configuration
          #
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
            {{- if .Values.av.enabled }}
            - name: av-tcp
              containerPort: 4443
              protocol: TCP
            - name: av-udp
              containerPort: 10000
              protocol: UDP
            {{- end }}
          
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /ct-health/
              port: http
          
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: /ct-health/
              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  
      {{- if .Values.securityContext.readOnlyRootFilesystem}}
      volumes:
        - name: codetogether-runtime
          emptyDir: {}
        - name: codetogether-tmp
          emptyDir:
            medium: Memory
      {{- else if .Values.favicon.enabled }}
      volumes:
        - name: favicon-volume
          configMap:
            name: {{ .Release.Name }}-favicon
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
