{{- if not .Values.intelsecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-intel
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.intel.url | b64enc | quote }}
  secret: {{ .Values.intel.secret | b64enc | quote }}
{{- end }}