{{- if and .Values.ai.enabled (eq .Values.ai.mode "external") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ai-config" (include "codetogether.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
data:
  ai_provider: {{ .Values.ai.provider | quote }}
  ai_url: {{ .Values.ai.url | quote }}
{{- end }}


