{{- if and .Values.ai.enabled (eq .Values.ai.mode "external") (or (not .Values.ai.externalSecret.name) .Values.ai.externalSecret.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ai.externalSecret.name | default (printf "%s-ai-external-secret" (include "codetogether.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-key: {{ .Values.ai.externalSecret.apiKey | quote }}
{{- end }}

