{{- if and .Values.ai.enabled (eq .Values.ai.mode "external") }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-external-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-key: {{ .Values.ai.apiKey | quote }}
{{- end }}

