{{- $extSecret := (index .Values.ai "externalSecret" | default dict) }}
{{- if and .Values.ai.enabled (eq .Values.ai.mode "external") (or (not $extSecret.name) $extSecret.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $extSecret.name | default (printf "%s-ai-external-secret" (include "codetogether.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-key: {{ $extSecret.apiKey | quote }}
{{- end }}

