apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.fullnameOverride }}{{ .Values.fullnameOverride }}-hqproperties{{ else }}hqproperties{{ end }}
type: Opaque
stringData:
  cthq.properties: |-
    {{- range $key, $value := .Values.hqproperties }}
      {{- if eq $key "hq.cassandra.db.username" }}
        {{- if $.Values.cassandra.passwordSecret }}
    {{ $key }}={{ (lookup "v1" "Secret" .Release.Namespace $.Values.cassandra.passwordSecret).data.cassandra.password | b64dec }}
        {{- else }}
    {{ $key }}={{ $value }}
        {{- end }}
      {{- else }}
    {{ $key }}={{ $value }}
      {{- end }}
    {{- end }}