apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.fullnameOverride }}{{ .Values.fullnameOverride }}-hqproperties{{ else }}hqproperties{{ end }}
type: Opaque
stringData:
  cthq.properties: |-
    {{- $cassandraPassword := "" }}
    {{- if and (hasKey .Values "cassandra") (hasKey .Values.cassandra "passwordSecret") .Values.cassandra.passwordSecret (lookup "v1" "Secret" .Release.Namespace .Values.cassandra.passwordSecret) }}
    {{- $cassandraPassword := (lookup "v1" "Secret" .Release.Namespace .Values.cassandra.passwordSecret).data.cassandraPassword | b64dec }}
    {{- end }}
    {{- range $key, $value := .Values.hqproperties }}
      {{- if and (eq $key "hq.cassandra.db.password") $cassandraPassword }}
    {{ $key }}={{ $cassandraPassword }}
      {{- else }}
    {{ $key }}={{ $value }}
      {{- end }}
    {{- end }}