{{- if not .Values.hqproperties.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.fullnameOverride }}{{ .Values.fullnameOverride }}-hqproperties{{ else }}hqproperties{{ end }}
type: Opaque
stringData:
  cthq.properties: |-
    {{- range $key, $value := .Values.hqproperties }}
       {{ $key }}={{ $value }}
    {{- end }}
{{- end }}
