{{- if .Values.ai.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
type: Opaque
data:
  {{- if .Values.ai.openai }}
  {{- if .Values.ai.openai.api_key }}
  openai-api-key: {{ .Values.ai.openai.api_key | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.ai.external }}
  {{- if .Values.ai.external.api_key }}
  external-ai-key: {{ .Values.ai.external.api_key | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
