apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.fullnameOverride }}{{ .Values.fullnameOverride }}-hqproperties{{ else }}hqproperties{{ end }}
type: Opaque
stringData:
  cthq.properties: |-
    {{- range $key, $value := .Values.hqproperties }}
      {{- if eq $key "hq.cassandra.db.username" }}
        {{- if .Values.cassandra.passwordSecret }}
    {{ $key }}={{ include "cassandra.password" .Values.cassandra.passwordSecret }}
        {{- else }}
    {{ $key }}={{ $value }}
        {{- end }}
      {{- else }}
    {{ $key }}={{ $value }}
      {{- end }}
    {{- end }}