apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
type: Opaque
data:
  {{- if and (.Values.ai.openai) (.Values.ai.openai.api_key) }}
  openai-api-key: {{ .Values.ai.openai.api_key | b64enc }}
  {{- end }}
  {{- if and (.Values.ai.external) (.Values.ai.external.api_key) }}
  external-ai-key: {{ .Values.ai.external.api_key | b64enc }}
  {{- end }}
