name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/portal/**

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: charts/portal
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.DEV_KUBE_CONFIG }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: deploy portal to dev
        run: |
          helm upgrade portal portal -n portal -f portal/values.yaml -f portal/environments/dev.yaml
